name: Hajk
favicon: null
layout_spectrum: 0.50208
typography_spectrum: 0.47916
title: Hajk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080d1d'
    - '#e6e8e7'
    - '#b2b6b3'
    - '#7e827f'
    - '#2a2a2a'
  brandStrength: 0.625
  lightness: 0.9795939216855913
  saturation: 0.375
  rhythmicContrast: 0.9151423557195812
purpose: []
