name: Hajk
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47916
title: Hajk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eb4737'
    - '#fefefe'
    - '#3e9fd5'
    - '#ef8e93'
    - '#81e6bb'
  brandStrength: 0.25
  lightness: 0.9795939216855913
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
